export const ADOPTION_PETS = [
  {
    id: 'adopt-1',
    name: 'Luna',
    breed: 'Labrador Retriever',
    gender: 'Hembra',
    age: '2 años',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCTL_gcpgsW-AufPgKW4Y8HSCFnS2KmiUcCWpUnxZhVMNZmlVJfh8yhANr3gZbCEywNT7RhtUFIU97Fck3BnrbILj4tr5yZip-U9DLGDHaDAepcoV76-xnjI7h7TFNgEII-h31Wh8je7sE2aivVx01_CjTmFgqumFM28m6erj8l3ezandcvdZf_9Z20e6Qj4Gp5dvcBAWG8SNt-4YBFIBbCI6_Mb03EkG67_2KePoHcD5MvifMyohRy',
    category: 'Perros',
    status: 'Saludable',
    description: 'Luna es una cachorra de labrador sumamente dulce y juguetona. Le encanta correr en el parque, es excelente con los niños y tiene todas sus vacunas al día.',
    temperament: ['Afectuosa', 'Activa', 'Inteligente', 'Sociable'],
    location: 'Colonia Roma, CDMX',
    size: 'Mediano',
    vaccinated: true,
    neutered: true,
  },
  {
    id: 'adopt-2',
    name: 'Max',
    breed: 'Mestizo de Tabby',
    gender: 'Macho',
    age: '1 año',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuArgUPc1HpHQE0mArpFYUVtq3pcRN-zUZKGA1JVMiYzb8Smy7fc5GfE_l-7zrc2HwzRxcDg0jPJQcePpyxQIYsL7W7Vxitk6BivB8padWeQZemSVF7bx4_2G5PxcDSJATduAxmcd1GUL3vllGt-8WNOYsGXGZaDWia-iwrPwjbziOnPNNU1e-4VrHmnPmjdi75KNU5pfi4d1h3b2szaFiyEdYG77VGJsvRpZdDO0EzJOU0OSAaXVsxu',
    category: 'Gatos',
    status: 'Urgente',
    description: 'Max es un gatito de un año muy curioso y ronroneador. Se adaptaría perfectamente a un departamento. ¡Le fascinan los juguetes con plumas!',
    temperament: ['Curioso', 'Cariñoso', 'Tranquilo', 'Independiente'],
    location: 'Condesa, CDMX',
    size: 'Pequeño',
    vaccinated: true,
    neutered: true,
  },
  {
    id: 'adopt-3',
    name: 'Oliver',
    breed: 'Border Collie Mix',
    gender: 'Macho',
    age: '5 meses',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBn4b_HEewe7VrNdER9MvhYVHQ5Z1oE-GigJ5i8W1XbQHu2rp1hI-rHXEx6tWDwJN4Sp7L4s3E2xR6OwrYL1cduWuR2-1Tl-ABdMBFfBOnprNwDD_yUx53dxNfuboPn6wlRue0FiIv3KGd0hnxIITZFIeZaA514xQ3N6JPIbbTQnj-BgjhdRy2rypm0vuwJtbspUuSElkSbJ_BXXMx73c19cZPMdYigjQ-djmaORfbsIRFhCOxqTNLB',
    category: 'Perros',
    status: 'Saludable',
    description: 'Oliver es un cachorro súper vivaz con el clásico pelaje blanco y negro de Border Collie. Es increíblemente inteligente y necesita estimulación mental y física continua.',
    temperament: ['Enérgico', 'Inteligente', 'Atento', 'Juguetón'],
    location: 'Polanco, CDMX',
    size: 'Pequeño-Mediano',
    vaccinated: true,
    neutered: false,
  },
];

export const LOST_REPORTS = [
  {
    id: 'lost-1',
    name: 'Max',
    breed: 'Golden Retriever',
    description: 'Llevaba un collar de tela azul con placa metálica. Es muy dócil y asustadizo. Se perdió en la Colonia Roma Norte.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBNhUD5st_mw-hyyCv0umr5p76HEwiyCKtjKfiQTpHQy3MchN2CNoPemUD5UCe0AfSjL-fPlswBWmJHEMEK6jP1n-_aYkajls8rIqcRHUoRhY1n0v1Do7ci2hqueM1jy99ZAxObyQAxHRkWlkW4A9UZg6s4d9UgYCjaFKEA8YNI_1FhMD8dvcaIKH8ZjV51Q9erPadpLu2LOEAdknrQF_UNBtRYsDNsh9z6yJuPCYfx0igwGspDtQqR',
    lastLocation: 'Colonia Roma, CDMX',
    lastSeenTime: '5:00 PM',
    reportedAt: 'Reportado Ayer',
    contactNumber: '+52 55 1234 5678',
    isUrgent: true,
    ownerName: 'Andrea Martínez',
    ownerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAGxtnF8_l_m4z3df-J-hvL4j-oGPdKQ0of7Pxef8efL8KlwoPXu5DRohpClHK9tGMkSirzJDDCF-6ek66p0N9NuRf-XaRrNk5ca0Gma7HAO3GSpjn3IEfRO9V_gDvI_8FtCrjiIYmds5VAWn4g2tSpvgRbqko70rmMp5GdF0ySUL-MV4g8JGs1QnVItzlcenKsa-nVr6ZDmznVXyupuxEmr22BKttsFSaOnJRqJyw7Ht09EbF96dTz',
  },
  {
    id: 'lost-2',
    name: 'Luna',
    breed: 'Gato Siamés',
    description: 'Gatito siamés de ojos azules muy llamativos. Tiene un collar azul marino con cascabel pequeño. Visto por última vez cerca del Parque Lincoln.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPgErH9PrVDUp6HC-vEtmRREWyE4pi4w5ebMSEgqn4wGIuRMTwtToM-eqbTDRJJqm1RoKRLKyT8oIiLfcK2luC9Iq-uB1R6CDGzQzlY_za757Y4KAsJ37__OlSJ0D46xS-DSGa5za6oBPWax-O4ZD-HCFyhfLvaYWwBiFSwVH-MPDPefpMAZPJk7_Dp995dSEzZQ5VKenBSTLlSo8nzemNq6U6myUFV4u990Cgtdj2Rj02cEUhuQmz',
    lastLocation: 'Polanco II Secc, CDMX',
    lastSeenTime: 'Visto cerca de Parque Lincoln',
    reportedAt: 'Hace 2 días',
    contactNumber: '+52 55 9876 5432',
    isUrgent: true,
    ownerName: 'Roberto Garza',
    ownerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAGxtnF8_l_m4z3df-J-hvL4j-oGPdKQ0of7Pxef8efL8KlwoPXu5DRohpClHK9tGMkSirzJDDCF-6ek66p0N9NuRf-XaRrNk5ca0Gma7HAO3GSpjn3IEfRO9V_gDvI_8FtCrjiIYmds5VAWn4g2tSpvgRbqko70rmMp5GdF0ySUL-MV4g8JGs1QnVItzlcenKsa-nVr6ZDmznVXyupuxEmr22BKttsFSaOnJRqJyw7Ht09EbF96dTz',
  },
];
